# See: https://docs.github.com/en/actions
# To get started: https://docs.github.com/en/actions/quickstart
name: Deploy Github Pages

# Run the following jobs on a manual dispatch
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Build project with Vite
        run: npm run build

      # Fix URL routing in Github Pages
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      # Deploy the resulting dist dir
      # This does not use the manual deploy-pages scripts
      - name: Deploy dist
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}